### PR TITLE
Replacing 1970-01-01 01:00:00 by 'never' fixes #105.

### LINKED ISSUE #105: Maybe convert 1970-01-01 01:00:00 to 'never' or empty string
The string 1970-01-01 01:00:00 means 'never' in most cases.
When users have never accessed a course, it states 1970-01-01 01:00:00 as their last access,
when the have never logged in, it states 1970-01-01 01:00:00 as their last login.
Maybe it would be possible to convert this to a (localized) 'never' string or leave that empty.
1970-01-01 01:00:00 is non-information and therefore noise.

Best,
Luca

### PR DESCRIPTION
**Pull request by lucaboesch**
I hope you like that fix.

It ships with a new .travis.yml config, too, to make Travis CI builds pass.
Also, I took the liberty to language specifically format the dates by using userdate and introducing a localisable 'strftimesecondsdatetimeshort' format, since no standard format with seconds included is built-in in Moodle.

Best,
Luca

### CODE REVIEW

**Comment by Nullmann** [comment]
Hello Luca,

thanks for looking at travis! 

I will only be able to look at it thoroughly next wednesday. I may have to change the date-string a bit as it was Year-Month-Day before to support native sorting in the tables.

Also, there is no need to introduce a new 'never'-string as there is one in the standard moodle distribution: https://github.com/moodle/moodle/blob/master/lang/en/moodle.php#L1309

Best,
Benedikt

**Comment by Nullmann** [comment]
I had a chance to look at this. I like the idead that there can be different string formats for different regions/languages, but I made a few edits:

- I used the moodle-core string for never (and retrieved it outside the user-loop to make it faster)
- For users listed in a course I still used the fixed Y-m-d H:i:s format because this is the only way to sort the table-row reliably. The "never" string is still used. 
-

**Comment by Nullmann** [comment]
I had to merge my master-branch to your commit because I added the duplicate-function earlier. Only the version.php had a conflict which needed to be solved.

**Comment by lucaboesch** [comment]
Great stuff, Benedikt.
I wanted to let you know I spotted a typo in the first line of the Readme.md

"all in one, intuitve window"
intuitve

Best,
Luca

**Pull request merged**
